run:
  timeout: 1m
  tests: false
  skip-files:
    - "testing.go"
    - ".*\\.pb\\.go"
    - ".*\\.gen\\.go"

linters-settings:
  goconst:
    min-len: 5
    min-occurrences: 4
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    #- gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    #- stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
